services:
  - type: web
    name: flask-audio-app
    env: python
    plan: free

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn newfile:app"

    build:
      pythonVersion: 3.10

    envVars:
      - key: GOOGLE_API_KEY
        value: your_actual_api_key_here

