services:
  - type: web
    name: flask-audio-app
    env: python
    plan: free

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn newfile:app"

    build:
      pythonVersion: 3.10  # ✅ correct placement under 'build'

    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyCsk0m7c-qpdbPUa4-4e1ERYhoNPsaWel4

