services:
  - type: web
    name: flask-audio-app
    env: python
    plan: free
    pythonVersion: 3.10

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn newfile:app"

    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyBnTFg7CNgZLB-gDA4GeP-Pv2DvBKktFKY

